algoritmo "semnome"
// Função :
// Autor :
// Data : 27/08/2020
// Seção de Declarações 
//const ovo,óleo,sal,fogo,ovofrito:Ingredientes
//Const frito:fritura
var  ovofrito:fritura

inicio
      ovofrito <- oleo+fogo
      Espera("1 Minuto")
      ovofrito <- ovofrito+ovo
      ovofrito <- ovofrito+sal
      Enquanto ovofrito <> frito
               Espera("1 Segundo")
               ovofrito <- ovofrito-fogo

fimalgoritmo
